### ISSUE TITLE
`src/` structure?

### ISSUE THREAD

**Issue by tony** [thisch/pytest-sphinx#44]
When a second potential .py file is considered, [setuptools plays better with `src/`](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout)

I've found it difficult in #38 to get the entrypoints and multiple modules in a flat structure to work correctly. It seems by design it doesn't work (or else people would be committing junk [[1](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout:~:text=If%20you%20are%20using%20auto%2Ddiscovery%20with%20flat%2Dlayout%2C%20setuptools%20will%20refuse%20to%20create%20distribution%20archives%20with%20multiple%20top%2Dlevel%20packages%20or%20modules.)]):

> If you are using auto-discovery with flat-layout, setuptools will refuse to create [distribution archives](https://packaging.python.org/en/latest/glossary/#term-Distribution-Package) with multiple top-level packages or modules.

>
> This is done to prevent common errors such as accidentally publishing code not meant for distribution (e.g. maintenance-related scripts).

>
> Users that purposefully want to create multi-package distributions are advised to use [Custom discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) or the src-layout.

**Comment by thisch** [comment]
I also had problems in several other projects that don't have a src/ structure. So I'm 👍🏿 on switching to a src/ structure.

**Comment by tony** [comment]
PR'd at #45 

I am also starting to adopt `src/` on projects - the only reason being the package systems of the day work better with it 🤷

**Comment by thisch** [comment]
Thx. Merged.
