### ISSUE TITLE
mypy? (if so, strength?)

### ISSUE THREAD

**Issue by tony** [thisch/pytest-sphinx#48]
Example of a strictly typed module: https://github.com/git-pull/gp-libs/blob/v0.0.1a9/src/pytest_doctest_docutils.py

Thoughts? Have you used [mypy](https://github.com/python/mypy) yet?

Basic mypy will pass out of the box on the project

**Comment by thisch** [comment]
I'm in favor of using mypy, because I think it makes the code more readable. Go ahead and add type annotations if you want ;)

**Comment by thisch** [comment]
I don't yet have a mypy config that we could use. Maybe we could re-use the one from pytest or maybe we are satisfied with the stock config, I don't have a stance on that.

**Comment by tony** [comment]
#50 is up

#47 (flake8 plugins) are up
