### ISSUE TITLE
Remove `_importconftest` call on pytest>=8

### ISSUE THREAD

**Issue by bluetech** [thisch/pytest-sphinx#58]
The plugin has some code which accesses some pytest internals to import conftests:

https://github.com/thisch/pytest-sphinx/blob/28f8f4ddf83615da43c138a2360b5246b9fe55b2/src/pytest_sphinx.py#L558-L563

Similar code was present in pytest's builtin doctest plugin, but I've removed it just now: https://github.com/pytest-dev/pytest/pull/11808

The code is no longer necessary on pytest>=8.0.0rc1 (possibly even before, but I'm not sure about that). It'd be great if pytest-sphinx remove it as well, so that it doesn't break if/when pytest breaks these internals.

**Comment by thisch** [comment]
Thx for the info @bluetech. I've just removed it.

**Comment by gauteh** [comment]
Also encountered this. Thanks for the fix. Anxiously awaiting the next release :D 

@knutfrode
